server:
  port: 8080
  servlet:
    context-path: /amaro

spring:
  profiles:
    active: ${PROFILE:}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: "jdbc:mysql://localhost:3306"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    encoding: UTF-8
    default-schema: "db_amaro"

logging:
  file:
    path: .
    name: amaro-backend.log
  level:
    root: info
    org:
      springframework:
      web: info
    br:
      com:
        amarobackend: debug